### ISSUE TITLE
SASS library no longer allows you to override the rem function native to CSS

### ISSUE THREAD

**Issue by monicagrimley** [Convertiv/handoff-app#76]
The npm sass library (https://www.npmjs.com/package/sass) in the latest release (1.65.1) appears to have changed the way functions are handled, if those functions names match exactly to native css functions.

The behavior in 1.65.1 is that native css functions get called rather than the declared function.  While that seems like reasonable behavior, it breaks the handoff build because we use a custom `rem()` function.

**Comment by bradmering** [comment]
In this release, we are going to pin the node sass library to `1.64.2` until we can rewrite the sass functions and implementation of bootstrap 5.2, 5.3 and the core site to not use the `rem` function name.
